### ISSUE TITLE
Look for descent asp.net free hosting

### ISSUE THREAD

**Issue by kirillkostrov** [kirillkostrov/scrutineer#1]

**Comment by vkamiansky** [comment]
There's a nice solution here. https://www.openshift.com/container-platform/features.html
A free hosting from the much beloved Red Hat. It supports .Net Core 1.0 to 2.0, sports Mongo DB, MySQL and Postgre and has a more-than-decent admin platform.

**Comment by vkamiansky** [comment]
Here's more info on how to debug an OpenShift-hosted .NET Core site with VS Code.
https://developers.redhat.com/blog/2017/10/23/remote-debug-asp-net-core-container-openshift-visual-studio-code/

**Comment by vkamiansky** [comment]
More theory on .Net Core and OpenShift.
https://developers.redhat.com/topics/dotnet/

**Comment by vkamiansky** [comment]
A walkthrough from Microsoft on how to create a simple ASP .Net Core 2.0 solution. https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc
